apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: argoproj.io
      kind: Application
      name: istio-.*
    path: version-patch.yaml