apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: 10
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.22.0
      chart: gateway
      helm:
        valueFiles:
        - '$values/apps/istio/base/values-gateway.yaml'
        ignoreMissingValueFiles: true
    - repoURL: 'https://github.com/BenjOst/argocdTest-ha-cloud-dev55.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
        - .webhooks[]?.failurePolicy
        - .webhooks[]?.namespaceSelector
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.failurePolicy